- hosts: all

  become: true
  become_method: sudo
  
  tasks:
    - name: pip
      import_role:
        name: geerlingguy.pip
    
    - name: Docker
      import_role:
        name: geerlingguy.docker